import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from "../../public/images/profile/banner.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import whitegif from "../../public/gifs/white.gif";
import { motion } from "framer-motion";
import AboutUs from '@/components/AboutUs';
import Adobe from '@/components/Adobe';
import Testimonials from '@/components/Testimonials';
import MyWork from '@/components/MyWork';

const FramerImage = motion(Image);

const FeaturedProjects = ({img}) => {
  return (
    <span className=" w-1/7 xs:w-10 sm:w-10 md:w-10 lg:w-11 xl:w-10 p-2 py-1 ml-5 cursor-pointer overflow-hidden border border-light 
    rounded-full">
      <FramerImage
        src={img}
        className=" w-5 h-7"
        whileHover={{ scale: 1.05 }}
        transition={{ duration: 0.2 }}
        priority
        sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"
      />
    </span>
  );
};


export default function Home() {
  // const isLight = useSelector((state) => state.theme.isLight);
  return (
    <>
      <Head>
        <title>Tay Dylan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <TransitionEffect /> */}
      <main
        className="flex min-h-screen xl:min-h-[50vh] xl:h-[50vh] md:min-h-screen items-center w-full xs:flex xs:items-center xs:justify-center sm:flex 
      sm:items-centers sm:justify-center  text-light 2xl"
      >
        <Layout
          className="pt-2 md:pt-16 sm:pt-8 xs:flex xs:items-center xs:justify-center sm:flex sm:items-centers 
          sm:justify-center lg:flex lg:items-centers  lg:justify-center xl:h-auto"
        >
          <div
            className="flex lg:flex-col w-full xl:h-[50vh] items-center justify-between lg:flex lg:items-centers 
          lg:justify-center "
          >
            <div className=" w-ful flex flex-col items-start self-center lg:w-full ">
              <p className="my-4 text-xl sm:!m-auto sm:!my-6 xs:!mx-0 font-medium md:text-sm sm:text-base xs:text-base">
                Hi there! I’m Tay Dylan Magwaro
              </p>
              <AnimatedText
                text="UI/UX Designer"
                className="!text-7xl sm:!text-center xs:!text-left xl:!text-5xl lg:!text-6xl md:!text-5xl sm:!text-4xl"
                // className={styles.fontStyle}
                style={{ fontFamily: "bold" }}
              />
              <div
                className="flex w-1/3 xl:w-1/2 xs:w-full md:w-2/4 items-center sm:self-center sm:mx-auto md:text-center
               md:justify-center self-start lg:self-start mt-2 xs:self-start xs:mx-0"
              >
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex w-full items-center sm:justify-center rounded-lg hover:underline overflow-hidden  group-hover:w-full 
                  transition-[width] ease duration-300  text-lg font-semibold capitalize text-light  hover:text-primary 
                  md:text-base dark:text-light hover:dark:text-light md:w-full xs:items-left xs:justify-start "
                  download={true}
                >
                  Discover Tay{" "}
                  <FeaturedProjects
                    img={whitegif}
                    className="w-20 xs:w-full "
                  />
                </Link>
              </div>
            </div>
            <div className=" w-[20vw] md:w-full xl:w-52 xl:-mt-40 xs:hidden md-hidden">
              <Image
                src={profilePic}
                alt="Tonde"
                className="w-full h-auto lg:hidden md:hidden"
                priority
                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"
              />
            </div>
          </div>
        </Layout>
      </main>
      <main className="">
        <AboutUs />
        <Adobe />
        <MyWork/>
        <Testimonials />
      </main>
    </>
  );
}


